# Create a program that will play the “cows and bulls” game with the user. The game works like this:
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number.
# For every digit that the user guessed correctly in the correct place, they have a “cow”.
# For every digit the user guessed correctly in the wrong place is a “bull.”
# Every time the user makes a guess, tell them how many “cows” and “bulls” they have.
# Once the user guesses the correct number, the game is over.
# Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.
# Say the number generated by the computer is 1038. An example interaction could look like this:
# Welcome to the Cows and Bulls Game!
# Enter a number:
# >>> 1234
# 2 cows, 0 bulls
# >>> 1256
# 1 cow, 0 bull
# Until the user guesses the number.

from random import randint

print('Guess a Four Digit Number!')
num = randint(1000, 9999)
guesses = 0

while 1 == 1:
    guesses += 1
    num_list = list(str(num))
    guess = list(str(input()))
    cow = 0
    bull = 0

    if guess == num_list:
        print('WIN')
        print(f'{guesses} guesses')
        break

    for i in range(0, 4):
        if guess[i] == num_list[i]:
            cow += 1
            guess[i] = 'x'
            num_list[i] = 'x'

    for i in range(0, 4):
        if guess[i] != 'x' and guess[i] in num_list:
            num_list[num_list.index(guess[i])] = 'x'
            bull += 1

    print(f'{cow} Cows : {bull} Bulls')
